### PR TITLE
Add awscli version support for linux. Fixes #9

### LINKED ISSUE #9: No means to upgrade or set specific version of awscli
Since awscli is a developing upstream software package, and thus a moving target, it's important to support upgrading or selecting a specific version of awscli. Do you plan to add something like this? Or would you welcome a patch to add an upgrade option? I've not yet taken on pip based package management through chef, so I'm a bit leery of doing this myself.

### PR DESCRIPTION
**Pull request by Crazybus**
Also refactored the rspec tests to allow setting attributes per test.

### CODE REVIEW

**Comment by nickryand** [comment]
@Crazybus thanks for the PR. I am going to pull it into my fork and update from there. I do not have access to this repository any longer. 

https://github.com/nickryand/awscli-cookbook

**Comment by Crazybus** [comment]
Great! Since you are the owner of the supermarket cookbook could you update the source to point to your fork? https://supermarket.chef.io/cookbooks/awscli

I'm planning on adding in configuration support too (https://github.com/awslabs/awscli-cookbook/issues/10). Should I still send the pull request here?

**Comment by nickryand** [comment]
Yup I was planning to update it within the next couple of days. I am also moving the python dependency from the python cookbook which is now deprecated over to the poise-python cookbook. 

Open the pull requests at my fork since I can merge PR's directly there. I'll merge in this PR by hand and refactor it to work with the poise-python cookbook.

**Comment by isuftin** [comment]
https://github.com/nickryand/awscli-cookbook == 404

**Comment by nickryand** [comment]
This had to go through a name change. A forked version of this cookbook is being maintained at: 
https://github.com/nickryand/cloudcli-cookbook

**Comment by hyandell** [comment]
Closing the pull request in favour of Nick's  https://github.com/nickryand/cloudcli-cookbook fork.

**Pull request closed without merging**
